please check what is wrong with shop and index template
thinknetica-django-lab-01/Kategkate pull request #34
Opened 2021-02-12 09:56 UTC by Kategkate

Сloses #7

2021-02-12 15:32 UTC, morgangt requested changes
в .gitignore надо добавить все фалы с расширением sqlite3, так: *.sqlite3

2021-02-12 15:32 UTC, morgangt commented on .idea/misc.xml
>  </project>
папку .idea надо добавить в файл .gitignore

2021-02-12 15:38 UTC, morgangt requested changes

2021-02-12 15:38 UTC, morgangt commented on main/main/settings.py
> +    'shop',
приложение shop надо добавить в конец списка

2021-02-12 15:43 UTC, morgangt requested changes

2021-02-12 15:43 UTC, morgangt commented on main/shop/views.py
> +    return render(request, 'shop/index.html')
адрес шаблон должен быть просто `'index.html'`

2021-02-15 10:33 UTC, Kategkate commented
Fixed all issues and done the task. Please, check

2021-02-16 09:01 UTC, morgangt approved these changes

2021-02-16 09:15 UTC, merged