filter(), save() and adding through admin has been implemented
thinknetica-django-lab-01/Kategkate pull request #48
Opened 2021-02-21 08:28 UTC by Kategkate

Closes #3

2021-02-21 11:24 UTC, Kategkate commented
closes #2

2021-02-21 12:20 UTC, Kategkate commented
added migration files

2021-02-22 12:17 UTC, morgangt requested changes

2021-02-22 12:17 UTC, morgangt commented on main/shop/models.py
> +        return '%s (%s)' % (self.id, self.item)
Используйте функцию format или f-string

2021-02-22 12:17 UTC, morgangt commented on main/queries.py
> +b = Category(name='Milk Burenka with 3,3% fat', help_text='Milk')
Не используйте однобуквенные переменные

2021-02-27 12:14 UTC, morgangt approved these changes

2021-03-01 11:02 UTC, merged